---
title: Data Wrangling using Tidyverse
author: DylanMcKenna
date: '2021-05-25'
slug: data-wrangling-using-tidyverse
categories:
  - tidyverse
tags: []
---


## Import the hotels.csv file

```{r warning=FALSE}
library(tidyverse)

hotels <- read_csv("hotels.csv")

head(hotels)
names(hotels)

```

## Select

```{r}
select(
  hotels, 
  lead_time
  )

select(hotels, hotel, lead_time)
```

## Using of pipe operator %>% to Select a variable
A pipe is used to pass information from one process to another.
```{r}

hotels %>%
  select(hotel, lead_time) %>%
  # desc is descending order
  arrange(desc(lead_time))

```

## Select a range of variables

```{r}

hotels %>%
  select(hotel:arrival_date_month)

hotels %>%
  select(starts_with("arrival"))
```

## Select a range of rows / cases

```{r}
hotels %>%
  slice(1:5)

hotels %>%
  filter(hotel == "City Hotel")

hotels %>%
  filter( 
    adults == 0,
    children >= 1
    ) %>% 
  select(adults, babies, children)

# bookings with no adults and some children or babies in the room
hotels %>%
  filter( 
    adults == 0,     
    children >= 1 & babies >= 1     # | means or  & means and
    ) %>%
  select(hotel, adults, babies, children)
```

## Summarizing

```{r}
hotels %>%
  count(hotel, market_segment)
```

## Mutate

Use mutate to create a new variable

These only stay on our computer. They do not change the existing hotels.csv file.

```{r}
little_ones <- hotels

# Created a copy of hotels called little_ones that only contains variables (children, babies, and little_ones)

little_ones %<>%
  mutate(little_ones = children + babies) %>%
  select(children, babies, little_ones) %>%
  arrange(desc(little_ones))



```



