---
title: Final Project
author: DylanMcKenna
date: '2021-06-27'
slug: final-project
categories:
  - ggplot2
  - shiny
  - tidyverse
tags: []
leafletmap: true

---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(shiny)
library(lubridate)
library(gghighlight)
library(janitor)
library(gghighlight)
library(ggrepel)
library(weathermetrics)
library(leaflet)
library(tidymodels)

```


## Description of Dataset


```{r echo=FALSE, warning=FALSE, error=FALSE}
# read in data
weather <- read.csv("weather.csv")

weather <- weather %>%
  rename(min_temp_f = TMIN,
         max_temp_f = TMAX,
         avg_temp_f = TAVG,
         avg_day_wind_mph = AWND,
         max_wind_5_dir_deg = WDF5,
         max_wind_5_spd_mph = WSF5,
         snowfall_in = SNOW,
         snowdepth_in = SNWD,
         precip_in = PRCP) 
  

```


```{r echo=FALSE, warning=FALSE, message=FALSE}
# convert fahrenheit to celsius for temperature variables
weather <- weather %>%
  mutate(min_temp_c = fahrenheit.to.celsius(min_temp_f, round = 2),
         max_temp_c = fahrenheit.to.celsius(max_temp_f, round = 2),
         avg_temp_c = fahrenheit.to.celsius(avg_temp_f, round = 2)) %>%
  select(-c(min_temp_f, max_temp_f, avg_temp_f))



# convert date to Date
weather <- weather %>%
  mutate(date = ymd(date))

# cumulative snowfall by station

# NOT REALLY USEFUL
weather_group_temp_max <- weather %>%
  group_by(station) %>%
  count(station, max_temp_c, latitude, longitude) %>%
  summarise(max_temp_c = max(max_temp_c),
            latitude = max(latitude),
            longitude = max(longitude)) %>%
  na.omit()


```




```{r echo=FALSE}

# Fit a line to the date
line_maxtemp_latitude <- linear_reg() %>%
  set_engine("lm") %>%
  fit(max_temp_c ~latitude  , data = weather_group_temp_max) %>%
  tidy()

chart_maxtemp_latitude <- ggplot(data = weather_group_temp_max, 
            aes(x = latitude, y = max_temp_c)) +
  geom_point(color = "#999999", alpha = 0.5) +
  #gghighlight(max(max_temp_c))+
  labs(
    title = "Latitude and Maximum Temperature Trend",
    x = "Latitude",
    y = "Maximum Temperature Observed (Celsius)"
    ) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 150)) +
  theme(plot.subtitle = element_text(colour = "#E48957", face = "bold", size = rel(1.5)))

chart_maxtemp_latitude <- chart_maxtemp_latitude +
  geom_smooth(formula = y ~ x, method = "lm", color = "#FF0000", fullrange = TRUE, se = FALSE) +
  theme_bw() +
  geom_text(data = subset(weather_group_temp_max, max_temp_c > 100),
            aes(max_temp_c, label = station))

chart_maxtemp_latitude
```

