---
title: Fun with R
author: DylanMcKenna
date: '2021-05-25'
slug: fun-with-r
categories:
  - Basics
tags: []
---

## Variables and Numbers

Internally stored as vectors.

```{r}

x <- 1

y = 2

3 -> z

x + y

y*z

y/x
```

## Vectors 

```{r}
a <- 0:10
print(a)
b <- 10:-4
print(b)

class(a)
str(a)

a[c(1, 5, 10)]
tail(a)
head(b, 4)
```

## Combine Operator for creating vectors

When we create a vector with multiple data types, R coerces the vetor to most compatible data type.

```{r}
c(1,2,4)
c(1,7:9)

c <- c(1:5, 10, 'red','yellow','green')

print(c)

class(c)
str(c)

d <- c(1:5, 10.5)

print(d)
class(d)
str(d)
```

## Sequency Operator Application

```{r}

x <- seq(0, 8*pi , length.out = 200)
y <- sin(x)
plot(x,y)

```

## Dropping Missing Values

```{r}
a <- c(3, -2,4,NA,-1,8,-4,9,NA,11,3,8,NA)

a[!is.na(a)]

a <-c(2,3,-1,3,5,2,-3,1)
print(paste("The sum of positive integers in a = ", sum(a[a>0])))

cat("The sum of positive integers in a = ", sum(a[a>0]))
```

## Matrix

```{r}
M1 <- matrix(1:12, ncol =4, byrow = TRUE)
M1
M2 <- matrix(1:12, nrow=4)
M2

# Accessing Matrix Elements
M1[2,3]
M1[3,]
M1[,3]
```

## Accessing Matrix Elements

```{r}
M3 <- matrix(1:20, ncol=4)
M3
M_Extracted <-  M3[c(3,5) , c(2,4)]
M_Extracted

```

## Data Frames

```{r}
# Building a data frame. Typicaly we will import the data frame. Example, Excel
DF <- data.frame(

gender = c("Male", "Male","Female"),

height = c(152, 171.5, 165),

weight = c(81,93, 78),

age =c(42,38,26),

row.names=c('Ally','Belinda','Alfred')
)

DF
# Use the $ after data frame name to select specific variable.

DF$age

# Filter Data Frame

DF[DF$gender == "Male",]

# Filter Data Using Subset


```



