---
title: Visualising Categorical Data using ggplot2
author: DylanMcKenna
date: '2021-05-21'
slug: visualising-categorical-data-using-ggplot2
categories: []
tags: []
---


# Lending Club - visualising categorical data
We can use bar plots, segmented bar plots, violin plots, and ridge plots.



## Bar Plot
The use of bar plots presents the data.


```{r}
library(openintro)
library(tidyverse)
ggplot(loans, aes(x = homeownership)) +
  geom_bar()

```


```{r}
library(openintro)
library(tidyverse)
ggplot(loans, aes(x = homeownership, 
                  fill = grade)) +
  geom_bar()
```


## Segmented Bar Plots
We can use segmented bar plots.


```{r}
ggplot(loans, aes(x = homeownership, fill = grade)) +
  geom_bar(position = "fill")
```


```{r}
ggplot(loans, aes(y = homeownership,
                  fill = grade)) +
  geom_bar(position = "fill") +
  labs(
    x = "Proportion",
    y = "Homeownership",
    fill = "Grade",
    title = "Grades of Lending Club loans",
    subtitle = "and homeownership of lendee"
  )
```

## Violin Plots

We can use violin plots.

```{r}
ggplot(loans, aes(x = homeownership, y = loan_amount)) +
  geom_violin()
```

## Ridge Plots
We can use ridge plots.

```{r warning=FALSE, error=FALSE}
library(ggridges)

ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) + 
  geom_density_ridges(alpha = 0.5)
```


